<a href="https://colab.research.google.com/github/HarshalPawar88/Bankruptcy-Prediction/blob/main/CAPSTONE_COMPANY_BANKRUPTCY_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem Statement**

Prediction of bankruptcy is a phenomenon of increasing interest to firms who
stand to loose money because on unpaid debts. Since computers can store huge dataset
pertaining to bankruptcy making accurate predictions from them before hand is becoming
important. 

The data were collected from the Taiwan Economic Journal for the years 1999 to 2009. Company bankruptcy was defined based on the business regulations of the Taiwan Stock Exchange.

 In this project you will use various classification algorithms on bankruptcy
dataset to predict bankruptcies with satisfying accuracies long before the actual event.

# **Attribute Information**

Updated column names and description to make the data easier to understand (Y = Output feature, X = Input features)

Y - Bankrupt?: Class label 1 : Yes , 0: No 

X1 - ROA(C) before interest and depreciation before interest: Return On Total Assets(C)

X2 - ROA(A) before interest and % after tax: Return On Total Assets(A)

X3 - ROA(B) before interest and depreciation after tax: Return On Total Assets(B)

X4 - Operating Gross Margin: Gross Profit/Net Sales

X5 - Realized Sales Gross Margin: Realized Gross Profit/Net Sales

X6 - Operating Profit Rate: Operating Income/Net Sales

X7 - Pre-tax net Interest Rate: Pre-Tax Income/Net Sales

X8 - After-tax net Interest Rate: Net Income/Net Sales

X9 - Non-industry income and expenditure/revenue: Net Non-operating Income Ratio

X10 - Continuous interest rate (after tax): Net Income-Exclude Disposal Gain or Loss/Net Sales

X11 - Operating Expense Rate: Operating Expenses/Net Sales

X12 - Research and development expense rate: (Research and Development Expenses)/Net Sales

X13 - Cash flow rate: Cash Flow from Operating/Current Liabilities

X14 - Interest-bearing debt interest rate: Interest-bearing Debt/Equity

X15 - Tax rate (A): Effective Tax Rate

X16 - Net Value Per Share (B): Book Value Per Share(B)

X17 - Net Value Per Share (A): Book Value Per Share(A)

X18 - Net Value Per Share (C): Book Value Per Share(C)

X19 - Persistent EPS in the Last Four Seasons: EPS-Net Income

X20 - Cash Flow Per Share

X21 - Revenue Per Share (Yuan ¥): Sales Per Share

X22 - Operating Profit Per Share (Yuan ¥): Operating Income Per Share

X23 - Per Share Net profit before tax (Yuan ¥): Pretax Income Per Share

X24 - Realized Sales Gross Profit Growth Rate

X25 - Operating Profit Growth Rate: Operating Income Growth

X26 - After-tax Net Profit Growth Rate: Net Income Growth

X27 - Regular Net Profit Growth Rate: Continuing Operating Income after Tax Growth

X28 - Continuous Net Profit Growth Rate: Net Income-Excluding Disposal Gain or Loss Growth

X29 - Total Asset Growth Rate: Total Asset Growth

X30 - Net Value Growth Rate: Total Equity Growth

X31 - Total Asset Return Growth Rate Ratio: Return on Total Asset Growth

X32 - Cash Reinvestment %: Cash Reinvestment Ratio

X33 - Current Ratio

X34 - Quick Ratio: Acid Test

X35 - Interest Expense Ratio: Interest Expenses/Total Revenue

X36 - Total debt/Total net worth: Total Liability/Equity Ratio

X37 - Debt ratio %: Liability/Total Assets

X38 - Net worth/Assets: Equity/Total Assets

X39 - Long-term fund suitability ratio (A): (Long-term Liability+Equity)/Fixed Assets

X40 - Borrowing dependency: Cost of Interest-bearing Debt

X41 - Contingent liabilities/Net worth: Contingent Liability/Equity

X42 - Operating profit/Paid-in capital: Operating Income/Capital

X43 - Net profit before tax/Paid-in capital: Pretax Income/Capital

X44 - Inventory and accounts receivable/Net value: (Inventory+Accounts Receivables)/Equity

X45 - Total Asset Turnover

X46 - Accounts Receivable Turnover

X47 - Average Collection Days: Days Receivable Outstanding

X48 - Inventory Turnover Rate (times)

X49 - Fixed Assets Turnover Frequency

X50 - Net Worth Turnover Rate (times): Equity Turnover

X51 - Revenue per person: Sales Per Employee

X52 - Operating profit per person: Operation Income Per Employee

X53 - Allocation rate per person: Fixed Assets Per Employee

X54 - Working Capital to Total Assets

X55 - Quick Assets/Total Assets

X56 - Current Assets/Total Assets

X57 - Cash/Total Assets

X58 - Quick Assets/Current Liability

X59 - Cash/Current Liability

X60 - Current Liability to Assets

X61 - Operating Funds to Liability

X62 - Inventory/Working Capital

X63 - Inventory/Current Liability

X64 - Current Liabilities/Liability

X65 - Working Capital/Equity

X66 - Current Liabilities/Equity

X67 - Long-term Liability to Current Assets

X68 - Retained Earnings to Total Assets

X69 - Total income/Total expense

X70 - Total expense/Assets

X71 - Current Asset Turnover Rate: Current Assets to Sales

X72 - Quick Asset Turnover Rate: Quick Assets to Sales

X73 - Working capitcal Turnover Rate: Working Capital to Sales

X74 - Cash Turnover Rate: Cash to Sales

X75 - Cash Flow to Sales

X76 - Fixed Assets to Assets

X77 - Current Liability to Liability

X78 - Current Liability to Equity

X79 - Equity to Long-term Liability

X80 - Cash Flow to Total Assets

X81 - Cash Flow to Liability

X82 - CFO to Assets

X83 - Cash Flow to Equity

X84 - Current Liability to Current Assets

X85 - Liability-Assets Flag: 1 if Total Liability exceeds Total Assets, 0 otherwise

X86 - Net Income to Total Assets

X87 - Total assets to GNP price

X88 - No-credit Interval

X89 - Gross Profit to Sales

X90 - Net Income to Stockholder's Equity

X91 - Liability to Equity

X92 - Degree of Financial Leverage (DFL)

X93 - Interest Coverage Ratio (Interest expense to EBIT)

X94 - Net Income Flag: 1 if Net Income is Negative for the last two years, 0 otherwise

X95 - Equity to Liability

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import imblearn
from imblearn.under_sampling import NearMiss
from collections import Counter
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, recall_score, precision_score, roc_auc_score
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE

In [ ]:
df_1=pd.read_csv('/content/drive/MyDrive/Alma Better/Capstone Project/Copy of COMPANY BANKRUPTCY PREDICTION.csv')

In [ ]:
pd.set_option('display.max_columns', 96)
pd.set_option('display.max_rows', 96)
df_1.head(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   

    ROA(B) before interest and depreciation after tax  \
0                                            0.40575    
1                                            0.51673    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   

    Continuous interest rate (after tax)   Operating Expense Rate  \
0                               0.780985                 0.000126   
1                               0.781506                 0.000290   

    Research and development expense rate   Cash flow rate  \
0                                     0.0         0.458143   
1                                     0.0         0.461867   

    Interest-bearing debt interest rate   Tax rate (A)  \
0                              0.000725            0.0   
1                              0.000647            0.0   

    Net Value Per Share (B)   Net Value Per Share (A)  \
0                  0.147950                  0.147950   
1                  0.182251                  0.182251   

    Net Value Per Share (C)   Persistent EPS in the Last Four Seasons  \
0                  0.147950                                  0.169141   
1                  0.182251                                  0.208944   

    Cash Flow Per Share   Revenue Per Share (Yuan ¥)  \
0              0.311664                     0.017560   
1              0.318137                     0.021144   

    Operating Profit Per Share (Yuan ¥)  \
0                              0.095921   
1                              0.093722   

    Per Share Net profit before tax (Yuan ¥)  \
0                                   0.138736   
1                                   0.169918   

    Realized Sales Gross Profit Growth Rate   Operating Profit Growth Rate  \
0                                  0.022102                       0.848195   
1                                  0.022080                       0.848088   

    After-tax Net Profit Growth Rate   Regular Net Profit Growth Rate  \
0                           0.688979                         0.688979   
1                           0.689693                         0.689702   

    Continuous Net Profit Growth Rate   Total Asset Growth Rate  \
0                            0.217535              4.980000e+09   
1                            0.217620              6.110000e+09   

    Net Value Growth Rate   Total Asset Return Growth Rate Ratio  \
0                0.000327                               0.263100   
1                0.000443                               0.264516   

    Cash Reinvestment %   Current Ratio   Quick Ratio  \
0              0.363725        0.002259      0.001208   
1              0.376709        0.006016      0.004039   

    Interest Expense Ratio   Total debt/Total net worth   Debt ratio %  \
0                 0.629951                     0.021266       0.207576   
1                 0.635172                     0.012502       0.171176   

    Net worth/Assets   Long-term fund suitability ratio (A)  \
0           0.792424                               0.005024   
1           0.828824                               0.005059   

    Borrowing depen

# **Exploratory Data Analysis**

In [ ]:
print(df_1.isna().sum().sum())
print(np.isnan(df_1).sum().sum())
print(df_1.isnull().sum().sum())

0
0
0


In [ ]:
list_1=[]
for i in df_1.columns:
  x=df_1[i].value_counts()
  if len(x)<=2:
    list_1.append(i)
  else:
    continue

In [ ]:
list_1

['Bankrupt?', ' Liability-Assets Flag', ' Net Income Flag']

### Liability-Assets Flag

In [ ]:
df_1[' Liability-Assets Flag'].unique()

array([0, 1])

In [ ]:
df_1[' Liability-Assets Flag'].value_counts()

0    6811
1       8
Name:  Liability-Assets Flag, dtype: int64

## **This feature has a very large class imbalance and we can drop this feature.**

## Net Income Flag

In [ ]:
df_1[' Net Income Flag'].unique()

array([1])

## **This feature has just one unique value and it wont be of any importance.**

In [ ]:
df_1.drop(columns=[' Net Income Flag', ' Liability-Assets Flag'],inplace=True)

In [ ]:
df_1.shape

(6819, 94)

In [ ]:
df_1.describe()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count  6819.000000                                        6819.000000          
mean      0.032263                                           0.505180          
std       0.176710                                           0.060686          
min       0.000000                                           0.000000          
25%       0.000000                                           0.476527          
50%       0.000000                                           0.502706          
75%       0.000000                                           0.535563          
max       1.000000                                           1.000000          

        ROA(A) before interest and % after tax  \
count                              6819.000000   
mean                                  0.558625   
std                                   0.065620   
min                                   0.000000   
25%                                   0.535543   
50%                                   0.559802   
75%                                   0.589157   
max                                   1.000000   

        ROA(B) before interest and depreciation after tax  \
count                                        6819.000000    
mean                                            0.553589    
std                                             0.061595    
min                                             0.000000    
25%                                             0.527277    
50%                                             0.552278    
75%                                             0.584105    
max                                             1.000000    

        Operating Gross Margin   Realized Sales Gross Margin  \
count              6819.000000                   6819.000000   
mean                  0.607948                      0.607929   
std                   0.016934                      0.016916   
min                   0.000000                      0.000000   
25%                   0.600445                      0.600434   
50%                   0.605997                      0.605976   
75%                   0.613914                      0.613842   
max                   1.000000                      1.000000   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count             6819.000000                 6819.000000   
mean                 0.998755                    0.797190   
std                  0.013010                    0.012869   
min                  0.000000                    0.000000   
25%                  0.998969                    0.797386   
50%                  0.999022                    0.797464   
75%                  0.999095                    0.797579   
max                  1.000000                    1.000000   

        After-tax net Interest Rate  \
count                   6819.000000   
mean                       0.809084   
std                        0.013601   
min                        0.000000   
25%                        0.809312   
50%                        0.809375   
75%                        0.809469   
max                        1.000000   

        Non-industry income and expenditure/revenue  \
count                                   6819.000000   
mean                                       0.303623   
std                                        0.011163   
min                                        0.000000   
25%                                        0.303466   
50%                                        0.303525   
75%                                        0.303585   
max                                        1.000000   

        Continuous interest rate (after tax)   Operating Expense Rate  \
count                            6819.000000             6.819000e+03   
mean                                0.781381             1.995347e+09   
std                                 0.012679             3.237684e+09   
min                 

# **Feature Selection**

In [ ]:
y_1=df_1['Bankrupt?']

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [ ]:
X_1=df_1.drop(columns='Bankrupt?')

In [ ]:
SelectKBest(chi2).fit(X_1, y_1)

SelectKBest(k=10, score_func=<function chi2 at 0x7f4bf98e7d40>)

In [ ]:
chi_score=pd.DataFrame(zip(X_1.columns,X_new.scores_),columns=['Name','Chi-Score'])
chi_score=chi_score.sort_values('Chi-Score', ascending= False).reset_index(drop=True)
#chi_score


In [ ]:
selected_columns=[i for i in chi_score['Name'][:27]]

In [ ]:
X_1=X_1[selected_columns]

In [ ]:
from pyod.models.abod import ABOD

# **Skewness**

In [ ]:
X_1.skew()

## **The features are largely skewed and we need to transfrom them.**

In [ ]:
from sklearn.preprocessing import PowerTransformer

In [ ]:
skewness=PowerTransformer()
X_3=pd.DataFrame(skewness.fit_transform(X_1), columns=X_1.columns)

/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:205: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:216: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims)


In [ ]:
#X_3.skew().sort_values()

# **Principal Component Analysis**

In [ ]:
#importing and fitting the data to the PCA
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(X_3)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
#checking the explained variance by the principal component
pca.explained_variance_ratio_

In [ ]:
pca.explained_variance_ratio_.sum()

1.0

In [ ]:
# transforming the principal components to the original values
X_3=pca.transform(X_3)[40:]

In [ ]:
s=StandardScaler()
X_4=s.fit_transform(X_3)
clf = ABOD(n_neighbors=31)
clf.fit(X_4)
trial=pd.DataFrame(zip(df_1['Bankrupt?'],clf.labels_,clf.decision_scores_), columns=['bankrupt','prediction','scores'])
print(len(trial[(trial['bankrupt']==1) & (trial['prediction']==1)]))
print(len(trial[(trial['bankrupt']==0) & (trial['prediction']==0)]))
print(len(trial[(trial['bankrupt']==0) & (trial['prediction']==1)]))
print(len(trial[(trial['bankrupt']==1) & (trial['prediction']==0)]))

26
5907
652
194


In [ ]:
confusion_matrix(trial['bankrupt'],trial['prediction'])

array([[5907,  652],
       [ 194,   26]])

In [ ]:
from pyod.models.ocsvm import OCSVM

In [ ]:
s=StandardScaler()
X_4=s.fit_transform(X_3)
clf = OCSVM(kernel='poly')
clf.fit(X_4)
trial=pd.DataFrame(zip(df_1['Bankrupt?'],clf.labels_,clf.decision_scores_), columns=['bankrupt','prediction','scores'])
print(len(trial[(trial['bankrupt']==1) & (trial['prediction']==1)]))
print(len(trial[(trial['bankrupt']==0) & (trial['prediction']==0)]))
print(len(trial[(trial['bankrupt']==0) & (trial['prediction']==1)]))
print(len(trial[(trial['bankrupt']==1) & (trial['prediction']==0)]))

24
5905
654
196


In [ ]:
confusion_matrix(trial['bankrupt'],trial['prediction'])

array([[5905,  654],
       [ 196,   24]])

In [ ]:
from pyod.models.lof import LOF

In [ ]:
#s=MinMaxScaler()
s=StandardScaler()
X_4=s.fit_transform(X_4)
clf = LOF(n_neighbors=30, contamination=0.04)
clf.fit(X_4)
trial=pd.DataFrame(zip(df_1['Bankrupt?'],clf.labels_,clf.decision_scores_), columns=['bankrupt','prediction','scores'])
print(len(trial[(trial['bankrupt']==1) & (trial['prediction']==1)]))
print(len(trial[(trial['bankrupt']==0) & (trial['prediction']==0)]))
print(len(trial[(trial['bankrupt']==0) & (trial['prediction']==1)]))
print(len(trial[(trial['bankrupt']==1) & (trial['prediction']==0)]))

10
6297
262
210


In [ ]:
confusion_matrix(trial['bankrupt'],trial['prediction'])

array([[6297,  262],
       [ 210,   10]])

# **1. KNN Algorithm- Without Under Sampling**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
y_1=df_1['Bankrupt?']
X_train, X_test, y_train, y_test= train_test_split(X_3,y_1, test_size=0.2, stratify=y_1)

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
scaler=StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neighbor = KNeighborsClassifier(n_neighbors=3)
neighbor.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
y_train_pred_1=neighbor.predict(X_train)
y_test_pred_1=neighbor.predict(X_test)

In [ ]:
confusion_matrix(y_train,y_train_pred_1)

array([[5268,   11],
       [ 122,   54]])

In [ ]:
confusion_matrix(y_test,y_test_pred_1)

array([[1315,    5],
       [  39,    5]])

In [ ]:
print(classification_report(y_train,y_train_pred_1))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      5279
           1       0.83      0.31      0.45       176

    accuracy                           0.98      5455
   macro avg       0.90      0.65      0.72      5455
weighted avg       0.97      0.98      0.97      5455



In [ ]:
print(classification_report(y_test,y_test_pred_1))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1320
           1       0.50      0.11      0.19        44

    accuracy                           0.97      1364
   macro avg       0.74      0.55      0.58      1364
weighted avg       0.96      0.97      0.96      1364



# **K-nn With Under Sampling**

# Under-Sampling

In [ ]:
# define the undersampling method
undersample = NearMiss(version=1, n_neighbors=3)
X, y = undersample.fit_resample(X_3, y_1)
counter = Counter(y)
print(counter)

Counter({0: 220, 1: 220})


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
scaler_knn=StandardScaler()
scaler_knn.fit(X_3)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X.shape

(440, 27)

In [ ]:
X=scaler_knn.transform(X)
X_3_scaled=scaler_knn.transform(X_3)

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
y_train_pred=neigh.predict(X)
y_test_pred=neigh.predict(X_3_scaled)

## **Train Classification Report**

In [ ]:
confusion_matrix(y,y_train_pred)

array([[210,  10],
       [ 56, 164]])

In [ ]:
print(classification_report(y,y_train_pred))

              precision    recall  f1-score   support

           0       0.79      0.95      0.86       220
           1       0.94      0.75      0.83       220

    accuracy                           0.85       440
   macro avg       0.87      0.85      0.85       440
weighted avg       0.87      0.85      0.85       440



## **Test Classification Report**

In [ ]:
confusion_matrix(y_1,y_test_pred)

array([[2862, 3737],
       [  56,  164]])

In [ ]:
print(classification_report(y_1,y_test_pred))

              precision    recall  f1-score   support

           0       0.98      0.43      0.60      6599
           1       0.04      0.75      0.08       220

    accuracy                           0.44      6819
   macro avg       0.51      0.59      0.34      6819
weighted avg       0.95      0.44      0.58      6819



In [ ]:
recall_score(y_1,y_test_pred)

0.7454545454545455

# **Support Vector Machine Without Under Sampling**

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='poly')
clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_train_pred=clf.predict(X_train)
svm_test_pred=clf.predict(X_test)

In [ ]:
confusion_matrix(y_train,svm_train_pred)

array([[5279,    0],
       [ 128,   48]])

In [ ]:
confusion_matrix(y_test,svm_test_pred)

array([[1318,    2],
       [  41,    3]])

# **SVM with Under Sampling**

In [ ]:
X.shape, y.shape

((440, 27), (440,))

In [ ]:
from sklearn import svm
clf_us = svm.SVC(kernel='poly')
clf_us.fit(X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
svm_train_pred_us=clf_us.predict(X)
svm_test_pred_us=clf_us.predict(X_3)

In [ ]:
confusion_matrix(y,svm_train_pred_us)

array([[215,   5],
       [ 84, 136]])

In [ ]:
confusion_matrix(y_1,svm_test_pred_us)

array([[5558, 1041],
       [  84,  136]])

In [ ]:
print(classification_report(y_1,svm_test_pred_us))

              precision    recall  f1-score   support

           0       0.99      0.84      0.91      6599
           1       0.12      0.62      0.19       220

    accuracy                           0.84      6819
   macro avg       0.55      0.73      0.55      6819
weighted avg       0.96      0.84      0.89      6819



In [ ]:
recall_score(y_1,svm_test_pred_us)

0.6181818181818182

In [ ]:
f1_score(y_1,svm_test_pred_us)

0.19470293486041515

# **Grid Search with SVM**

In [ ]:
clf_tf = svm.SVC()
paramgrid=dict(gamma=[0.001,0.01,0.1,1], C=[0.0001,0.001,0.01,0.1,1.0],kernel=['rbf','linear','sigmoid','poly'])
model=GridSearchCV(clf_tf,param_grid=paramgrid,cv=5, scoring='f1')
model.fit(X,y)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.0001, 0.001, 0.01, 0.1, 1.0],
                         'gamma': [0.001, 0.01, 0.1, 1],
                         'kernel': ['rbf', 'linear', 'sigmoid', 'poly']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1', verbose=0)

In [ ]:
model.best_params_

{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}

In [ ]:
gs_train_pred_svm=model.predict(X)
gs_test_pred_svm=model.predict(X_3)

In [ ]:
confusion_matrix(y,gs_train_pred_svm)

array([[192,  28],
       [ 32, 188]])

In [ ]:
confusion_matrix(y_1,gs_test_pred_svm)

array([[1077, 5522],
       [  32,  188]])

In [ ]:
print(classification_report(y_1,gs_test_pred_svm))

              precision    recall  f1-score   support

           0       0.97      0.16      0.28      6599
           1       0.03      0.85      0.06       220

    accuracy                           0.19      6819
   macro avg       0.50      0.51      0.17      6819
weighted avg       0.94      0.19      0.27      6819



In [ ]:
accuracy_score(y_1,gs_test_pred_svm)

0.18551107200469277

# **Over Sampling**

In [ ]:
X_3.head()

Cash/Current Liability   Fixed Assets to Assets   Net Value Growth Rate  \
0                -0.476012                 1.013107               -0.479175   
1                -0.429795                 1.165155               -0.170625   
2                 8.672937                 0.383636               -0.294089   
3                -0.443715                 1.432375               -0.331289   
4                -0.456050                 0.545202               -0.181440   

    Fixed Assets Turnover Frequency   Revenue per person  \
0                         -0.469977             0.459776   
1                          2.127741            -1.014307   
2                          2.132635             0.239932   
3                          2.136041            -0.459064   
4                         -0.469864             1.226443   

    Total assets to GNP price   Quick Ratio   Quick Asset Turnover Rate  \
0                    0.155886     -0.896658                    1.373899   
1                    0.100802     -0.608262                    1.378773   
2                    1.808762     -0.477983                   -0.732712   
3                   -0.219233     -0.723598                    1.371481   
4                   -0.179002     -0.639598                    1.365918   

    Total Asset Growth Rate   Research and development expense rate  \
0                  0.216011                               -1.191524   
1                  0.385896                               -1.191524   
2                  0.540081                                0.238525   
3                  0.199728                               -1.191524   
4                  0.298709                               -1.191524   

    Cash Turnover Rate   Total debt/Total net worth  \
0             0.483345                     1.731241   
1             0.757942                     0.690373   
2             0.562659                     1.729206   
3             0.723252                     0.312412   
4             0.575313                    -0.288966   

    Current Asset Turnover Rate   Interest-bearing debt interest rate  \
0                      2.120426                             -0.182021   
1                     -0.470330                             -0.182721   
2                     -0.469273                             -0.181438   
3                      2.129050                             -0.184499   
4                      2.128527                             -0.182371   

    Average Collection Days   Operating Expense Rate  \
0                 -0.548116                -0.709170   
1                 -0.341441                -0.709132   
2                 -0.440751                -0.709144   
3                 -0.587909                -0.709174   
4                 -0.420527                 1.425443   

    Accounts Receivable Turnover   Quick Assets/Current Liability  \
0                      -0.028669                        -1.077287   
1                      -0.106316                        -0.774894   
2                      -0.075496                        -0.484080   
3                      -0.006363                        -0.939030   
4                      -0.082372                        -0.755814   

    Allocation rate per person   Revenue Per Share (Yuan ¥)   Current Ratio  \
0                     1.287201                    -0.645168       -1.721960   
1                    -0.032030                    -0.478398       -0.978756   
2                     4.333121                    -1.237885       -0.092495   
3                     0.485021                    -0.799812       -1.323304   
4                     0.629591                    -0.108517       -0.977625   

    Inventory Turnover Rate (times)   Inventory/Current Liability  \
0                         -0.870125                     -0.299637   
1                          1.221480                     -0.196925   
2                          0.916532                      0.011014   
3                

In [ ]:
oversample = SMOTE()
X_o, y_o = oversample.fit_resample(X_3, y_1)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
X_o.shape,y_o.shape

((13198, 27), (13198,))

In [ ]:
X_o_train,X_o_test,y_o_train,y_o_test=train_test_split(X_o,y_o,test_size=0.25,stratify=y_o, random_state=99)
sc=StandardScaler()
sc.fit(X_o_train)
X_train_ov=sc.transform(X_o_train)
X_test_ov=sc.transform(X_o_test)
clf_tf_o = svm.SVC(kernel='poly',C=0.1, gamma=1)
clf_tf_o.fit(X_train_ov,y_o_train)
over_train_pred=clf_tf_o.predict(X_train_ov)
over_test_pred=clf_tf_o.predict(X_test_ov)
# X_3_scaled_new=sc.transform(X_3)
# x=f1_score(y_1,clf_tf_o.predict(X_3_scaled_new))



In [ ]:
confusion_matrix(y_o_train,over_train_pred)

array([[4948,    1],
       [   0, 4949]])

In [ ]:
confusion_matrix(y_o_test,over_test_pred)

array([[1566,   84],
       [   2, 1648]])

In [ ]:
print(classification_report(y_o_train, over_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4949
           1       1.00      1.00      1.00      4949

    accuracy                           1.00      9898
   macro avg       1.00      1.00      1.00      9898
weighted avg       1.00      1.00      1.00      9898



In [ ]:
print(classification_report(y_o_test, over_test_pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97      1650
           1       0.95      1.00      0.97      1650

    accuracy                           0.97      3300
   macro avg       0.98      0.97      0.97      3300
weighted avg       0.98      0.97      0.97      3300



In [ ]:
f1_score(y_o_test, over_test_pred)

0.9745712596096984

## **Original Dataset**

In [ ]:
X_3_scaled_new=sc.transform(X_3)

In [ ]:
confusion_matrix(y_1,clf_tf_o.predict(X_3_scaled_new))

array([[6514,   85],
       [   0,  220]])

In [ ]:
print(classification_report(y_1,clf_tf_o.predict(X_3_scaled_new)))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      6599
           1       0.72      1.00      0.84       220

    accuracy                           0.99      6819
   macro avg       0.86      0.99      0.92      6819
weighted avg       0.99      0.99      0.99      6819



In [ ]:
f1_score(y_1,clf_tf_o.predict(X_3_scaled_new))

0.8380952380952381

In [ ]:
roc_auc_score(y_1,clf_tf_o.predict(X_3_scaled_new))

0.9935596302470071